// Generated by https://quicktype.io

export interface SidenavMenu {
  routerFlag: string;
  header:     Header;
  lists:      List[];
}

export interface Header {
  icon:        string;
  description: string;
}

export interface List {
  link:      string;
  linkTitle: string;
}
